NXDRIVE-1614: Improve the Action class implementation
* Add Action.export().
* Remove all class attributes but 2 required ones.
* Add tests/unit/test_action.py.

Ultimately, this error should be gone forever:

    Fix AttributeError: 'FileAction' object has no attribute 'size'