NXDRIVE-2479: Improve S3 class import (#2467)
Prevent that error when the import will be made lazily:

    ImportError: cannot import name 'UploaderS3' from partially initialized module 'nuxeo.handlers.s3' (most likely due to a circular import)

Also log the cause of an upload error to help debug.