NXDRIVE-374: Fix error handling
Instead of catching too specific exceptions, let's catch them all.

Here it was done to bypass:

    FileNotFoundError: [Errno 2] No such file or directory: 'gio': 'gio'