Revert "Update sentry-sdk from 0.7.3 to 0.7.4"
This reverts commit f379aed8373eed4654f6186e04dd7b3a7708d6b9.

It causes a fatal error on macOS:

    ModuleNotFoundError: No module named 'sentry_sdk.integrations.logging'

Will take time later to investigate, but this is not a priority.