NXDRIVE-2380: [Direct Edit] Fix a regression when the provided digestAlgorithm is None
    AttributeError: 'NoneType' object has no attribute 'encode'
      File "nxdrive/direct_edit.py", line 552, in edit
      File "nxdrive/direct_edit.py", line 530, in _prepare_edit

Also:

- Fixed potential similar issues with `mime-type` and `data`.
- Fixed the code guessing the digest from the algo that was using the algo itself.