NXDRIVE-1500: Skip Sentry warnings in tests
test_local_move_with_remote_error() is in error due to:

>       assert not warnings
E       assert not ["sentry_sdk\\utils.py:300 invalid escape sequence '\\e'"]